language: cpp

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8

env:
  - GITHUB_TOKEN=a27573e27bea23fb05393ead69511b09e3b224be
cache:
  directories:
    - $HOME/.dotnet
    - $HOME/.nuget
addons:
  artifacts:
    s3_region: "us-west-2"
    paths: $(ls powershell*{deb,pkg} | tr "\n" ":")
git:
  submodules: false
install:
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - git submodule update --init
  - (cd tools && ./download.sh)
script:
  - ulimit -n 4096; powershell -c "Import-Module ./build.psm1; Start-PSBootstrap -Package; Start-PSBuild -Publish; Start-PSPackage; Start-PSPester; Start-PSxUnit"
