language: cpp

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode7.3

matrix:
  allow_failures:
    - os: osx
  fast_finish: true

addons:
  artifacts:
    paths: $(ls powershell*{deb,pkg} | tr "\n" ":")

install:
  - pushd tools
  - ./download.sh
  - popd
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm use 2.2.1; fi # Default 2.0.0 Ruby is buggy

script: ./tools/travis.sh
