language: cpp
sudo: required
dist: trusty
git:
  submodules: false
before_install:
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - git submodule update --init --recursive -- src/libpsl-native src/monad src/windows-build test/Pester
  - sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get -qq update
  - sudo apt-get install -y dotnet-nightly
script:
  - dotnet restore
  - ./build.sh
  - ./pester.sh
